# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Cloudflare Sync

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - cf-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public-pages
          path: ./public
      - name: Check public directory
        run: ls public
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: drawjourney # e.g. 'my-project'
          directory: ./public # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
